module.exports = {
    PRODUCTS_NOT_FOUND: "Products Not Found!",
    PRODUCT_CATEGORY_NOT_FOUND: "Product Category Not Found!",
    PRODUCT_NOT_INSERTED: "Product Not Inserted!",
    ATTENDANCE_NOT_CREATED: "Attendance Not Created!",
    ATTENDANCE_NOT_UPDATED: "Attendance Not Updated!",
    ATTENDANCE_NOT_FETCHED: "Attendance Not Fetched!",
    RECANCILIATION_NOT_CREATED: "Recanciliation Not Created!",
    RECANCILIATION_NOT_UPDATED: "Recanciliation Not Updated!",
    DISTRIBUTOR_NOT_FOUND: "Distributor Not Found!",
    USER_NOT_FOUND: "User Not Found!",
    USER_ALREADY_EXISTS: "User Already Exists!",
    INVALID_ID: "Invalid Id!",
    PRODUCT_DETAIL_NOT_UPDATED: "Product Detail Not Updated!",
    PASSWORD_IS_INCORRECT: "Password Is Incorrect!",
    SHOP_NOT_ADDED: "Shop Not Added!",
    SHOP_NOT_UPDATED: "Shop Not Updated!",
    SHOP_NOT_DELETED: "Shop Not Deleted!",
    USER_NOT_DELETED: "User Not Deleted!",
    USER_NOT_UPDATED: "User Not Updated!",
    USER_NOT_ADDED: "User Not Added!",
    SHOPS_NOT_FOUND: "Shops Not Found!",
    STATUS_NOT_UPDATED: "Status Not Updated!",
    UNEXPECTED_ERROR: "Unexpected Error!"
}
